### ISSUE TITLE
release on Maven again

### ISSUE THREAD

**Issue by garfieldnate** [dbtsai/lbfgs#2]
I'm trying to convert a project I have to use Maven, and it has a depency on LBFGS. The API of the one on Maven is slightly different; the LBFGS.lbfgs code is a method instead of a function, and I'm not sure if a new object is supposed to be created before each call or if it only needs one instantiation, etc. The project I'm using uses the same API as in this code base (static lbfgs function).

**Comment by dbtsai** [comment]
Thank you for your interest. However, I'm not maintaining this package anymore. Feel free to fork it. I would suggest to use the lbfgs in breeze which is well maintained. Thanks.

**Comment by garfieldnate** [comment]
Thanks for the pointer. I was able to use the package you released by simply instantiating an LBFGS object once, so I will stick with that. The one from breeze requires more setup, so I will shelf it for now.
